name: CD
on:
  push:
    branches: ['dev','main']
  pull_request:
    branches: ['dev','main']
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: remove unneccessary config files
        working-directory: ./meow-team-front
        run: |
          find /path/to/search -type f \( -name "docker-compose.yml" -o -name ".dockerignore" -o -name "Dockerfile" -o -name "default.conf" \) -print | xargs rm -f
      - name: update server & deliver last version
        working-directory: ./meow-team-front
        env: 
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@5
          liara deploy --app="meow-team-front" --api-token="$LIARA_TOKEN" --no-app-logs
